# Generated by Django 5.1.2 on 2024-10-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_type", models.CharField(max_length=100)),
                ("submission_time", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="queued", max_length=20)),
                ("result", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
