# Generated by Django 5.1.2 on 2024-10-14 11:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="job_type",
            new_name="title",
        ),
    ]
